theme = "theme"

[editor]
line-number = "relative"
mouse = false
bufferline = "multiple"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
