[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log", "serve"]

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[language-server.golangci-lint-lsp]
command = "golangci-lint"

[[language-server.taplo.config]]
root_dir = [".git", "*.toml"]

[language-server.kdl-lsp]
command = "kdl-lsp"

[language-server.v-analyzer]
command = "v-analyzer"

[[language]]
name = "v"
scope = "source.v"
roots = ["v.mod", ".git"]
formatter = { command = "v", args = ["fmt", "-"] }
language-servers = ["v-analyzer"]
auto-format = true

[[language]]
name = "json"
formatter = { command = "prettier", args = [
  "--stdin-filepath",
  "%{buffer_name}",
] }

[[language]]
name = "toml"
formatter = { command = "taplo", args = ["format", "-"] }
auto-format = true

[[language]]
name = "go"
formatter = { command = "gofmt" }

[[language]]
name = "kdl"
language-servers = ["kdl-lsp"]
