
[language-server.gopls]
command = "gopls"
args = ["-logfile=/tmp/gopls.log", "serve"]

[language-server.gopls.config]
"ui.diagnostic.staticcheck" = true

[language-server.golangci-lint-lsp]
command = "golangci-lint"

[[language]]
name = "go"
formatter = { command = "gofmt"}

[[language]]
name = "kdl"
language-servers = ["kdl-lsp"]

