"$schema" = "https://starship.rs/config-schema.json"

format = '''
$directory$git_status
$character'''
add_newline = true
scan_timeout = 50

[directory]
read_only = " ro"
style = "white"

[character]
success_symbol = "[*](white)"
error_symbol = "[*](bold red)"

[username]
format = '\[[$user]($style)\]'



